// <auto-generated />
using System;
using Lavanderia.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Lavanderia.Infra.Migrations
{
    [DbContext(typeof(LavanderiaContext))]
    partial class LavanderiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Lavanderia.Domain.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Documento")
                        .HasColumnName("documento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("telefone")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Lavanderia.Domain.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("decimal(15,5)");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Lavanderia.Domain.Models.ItensOrdens", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnName("item_id")
                        .HasColumnType("bigint");

                    b.Property<long>("OrdemId")
                        .HasColumnName("ordem_id")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId", "OrdemId")
                        .HasName("pk_itens_ordem");

                    b.HasIndex("OrdemId")
                        .HasName("ix_itens_ordem_ordem_id");

                    b.ToTable("itens_ordem");
                });

            modelBuilder.Entity("Lavanderia.Domain.Models.OrdemServico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ClienteId")
                        .HasColumnName("cliente_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnName("data_entrada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnName("data_saida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnName("valor_total")
                        .HasColumnType("decimal(15,5)");

                    b.HasKey("Id")
                        .HasName("pk_ordems_servicos");

                    b.HasIndex("ClienteId")
                        .HasName("ix_ordems_servicos_cliente_id");

                    b.ToTable("ordems_servicos");
                });

            modelBuilder.Entity("Lavanderia.Domain.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("login")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("senha")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Lavanderia.Domain.Models.ItensOrdens", b =>
                {
                    b.HasOne("Lavanderia.Domain.Models.Item", "Item")
                        .WithMany("Items")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("fk_itens_ordem_items_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lavanderia.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany("Items")
                        .HasForeignKey("OrdemId")
                        .HasConstraintName("fk_itens_ordem_ordems_servicos_ordem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lavanderia.Domain.Models.OrdemServico", b =>
                {
                    b.HasOne("Lavanderia.Domain.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_ordems_servicos_clientes_cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
